export const initialDrinks = [
	{
		id: "espresso-single",
		name: "Espresso (Single)",
		category: "Coffee",
		serving_style: "Shot",
		caffeine_mg: 63,
		volume_ml: 30,
		description: "A single shot of concentrated coffee.",
	},
	{
		id: "espresso-double",
		name: "Espresso (Double)",
		category: "Coffee",
		serving_style: "Shot",
		caffeine_mg: 126,
		volume_ml: 60,
		description: "Two shots of espresso.",
	},
	{
		id: "americano",
		name: "Americano",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 150,
		volume_ml: 350,
		description: "Espresso shots with hot water.",
	},
	{
		id: "cappuccino",
		name: "Cappuccino",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 150,
		volume_ml: 240,
		description: "Equal parts espresso, steamed milk, and foam.",
	},
	{
		id: "latte",
		name: "Caffe Latte",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 150,
		volume_ml: 470,
		description: "Espresso with plenty of steamed milk and a light foam.",
	},
	{
		id: "flat-white",
		name: "Flat White",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 130,
		volume_ml: 240,
		description: "Double shot of espresso with microfoam.",
	},
	{
		id: "cold-brew",
		name: "Cold Brew",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 200,
		volume_ml: 470,
		description: "Steeped in cold water for 12+ hours; high caffeine.",
	},
	{
		id: "iced-coffee",
		name: "Iced Coffee",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 165,
		volume_ml: 470,
		description: "Brewed hot coffee served over ice.",
	},
	{
		id: "mocha",
		name: "Caffe Mocha",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 175,
		volume_ml: 470,
		description: "Espresso, chocolate, and steamed milk.",
	},
	{
		id: "macchiato",
		name: "Espresso Macchiato",
		category: "Coffee",
		serving_style: "Shot",
		caffeine_mg: 63,
		volume_ml: 60,
		description: "Espresso stained with a dollop of foam.",
	},
	{
		id: "cortado",
		name: "Cortado",
		category: "Coffee",
		serving_style: "Shot",
		caffeine_mg: 126,
		volume_ml: 130,
		description: "Equal parts espresso and warm milk.",
	},
	{
		id: "drip-coffee",
		name: "Drip/Brewed Coffee",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 155,
		volume_ml: 350,
		description: "Classic filter coffee.",
	},
	{
		id: "filter-coffee",
		name: "Filter Coffee",
		category: "Coffee",
		serving_style: "Cup",
		caffeine_mg: 145,
		volume_ml: 240,
		description:
			"Smooth, light-bodied coffee brewed by dripping hot water over grounds.",
	},
	{
		id: "monster-energy",
		name: "Monster Energy",
		category: "Energy",
		serving_style: "Can",
		caffeine_mg: 160,
		volume_ml: 500,
		description: "Iconic 'Green' Monster with a heavy caffeine punch.",
	},
	{
		id: "celsius-live-fit",
		name: "Celsius",
		category: "Energy",
		serving_style: "Can",
		caffeine_mg: 200,
		volume_ml: 355,
		description: "Fitness-focused energy drink with ginger and green tea.",
	},
	{
		id: "reign-total-body",
		name: "Reign",
		category: "Energy",
		serving_style: "Can",
		caffeine_mg: 300,
		volume_ml: 500,
		description: "High-performance fuel with BCAAs and 300mg caffeine.",
	},
	{
		id: "english-breakfast",
		name: "English Breakfast Tea",
		category: "Tea",
		serving_style: "Cup",
		caffeine_mg: 50,
		volume_ml: 240,
		description: "Robust black tea, usually served with milk.",
	},
	{
		id: "earl-grey",
		name: "Earl Grey",
		category: "Tea",
		serving_style: "Cup",
		caffeine_mg: 45,
		volume_ml: 240,
		description: "Black tea flavored with oil of bergamot.",
	},
	{
		id: "green-tea",
		name: "Green Tea (Sencha)",
		category: "Tea",
		serving_style: "Cup",
		caffeine_mg: 35,
		volume_ml: 240,
		description: "Unoxidized leaves with a fresh, grassy flavor.",
	},
	{
		id: "matcha-latte",
		name: "Matcha Latte",
		category: "Tea",
		serving_style: "Cup",
		caffeine_mg: 70,
		volume_ml: 350,
		description: "Ground green tea powder whisked with milk.",
	},
	{
		id: "yerba-mate",
		name: "Yerba Mate",
		category: "Tea",
		serving_style: "Cup",
		caffeine_mg: 85,
		volume_ml: 240,
		description: "Traditional South American herbal tea with a strong kick.",
	},
];
